Chtitux\EtudiantBundle\Entity\Etudiant:
  type: entity
  table: etudiant
  repositoryClass: Chtitux\EtudiantBundle\Repository\EtudiantRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
      firstname:        { type: string, length: 255 }
      lastname:         { type: string, length: 255 }
      gender:           { type: string, length: 25 }
      description:      { type: string, length: 4000 }
  manyToOne:
      promotion:
          targetEntity: Promotion
          mappedBy: etudiant
#           joinColumn:
#             name: promotion_id
#             referencedColumnName: id
      filiere:
          targetEntity: Filiere
          mappedBy: etudiant
#           joinColumn:
#             name: filiere_id
#             referencedColumnName: id