# ./Resources/config/routing.yml

etudiant_list:
    pattern:  /etudiants/
    defaults: { _controller: ChtituxEtudiantBundle:Etudiant:index }

etudiant_show:
    pattern:  /etudiants/{id}
    defaults: { _controller: ChtituxEtudiantBundle:Etudiant:show }


promotion_list:
    pattern:  /promotions/
    defaults: { _controller: ChtituxEtudiantBundle:Promotion:index }

promotion_show:
    pattern:  /promotions/{id}
    defaults: { _controller: ChtituxEtudiantBundle:Promotion:show }


filiere_list:
    pattern:  /filieres/
    defaults: { _controller: ChtituxEtudiantBundle:Filiere:index }

filiere_show:
    pattern:  /filieres/{id}
    defaults: { _controller: ChtituxEtudiantBundle:Filiere:show }
